### PR TITLE
Add support for cstruct 6.0.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
As a side-effect, this also brings support for OCaml 4.12

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
ah, mh, is there a reason the latests releases are not on opam?

**Comment by psafont** [comment]
I think that since @mseri left Citrix the xapi packages haven't been published to the default opam repo.

There are 28 packages in the opam repository that are hosted in this github org:

```
cdrom
crc
dlm
ezxenstore
fd-send-recv
libvhd
message-switch
nbd
netlink
opasswd
vhdlib
vhd-tool
xapi-backtrace
xapi-forkexecd
xapi-idl
xapi-inventory
xapi-libs-transitional
xapi-rrd
xapi-rrdd
xapi-rrd-transport
xapi-stdext
xapi-tapctl
xapi-xenops
xen-api-client
xenctrl
xen-evtchn
xen-gnt
xenstore_transport
```

I would propose to remove from the repository the xapi daemons as well as xapi-idl (their interfaces) since I don't think they are useful for the community at large (they are not reusable) and add a script (maybe even into it's own ci pipeline?) that checks if the remaining packages have are up-to-date in the default opam repo.

**Comment by lindig** [comment]
What changes are adding support for cstruct? The code changes look syntactical to me. Is this about metadata?

**Comment by psafont** [comment]
It's a naming conflict, `Cstruct.length` takes precedence over the locally-defined `length`

**Review by psafont — APPROVED** [review]

**Review by lindig — APPROVED** [review]

**Comment by psafont** [comment]
@kit-ty-kate this repository requires developers to sign-off commit as a way to state that they have rights to commit the changes.

Could you run `git rebase master --signoff` to get them both signed?

**Comment by kit-ty-kate** [comment]
> Could you run `git rebase master --signoff` to get them both signed?

done

**Comment by psafont** [comment]
Thanks! I've added the new version of the package to https://github.com/ocaml/opam-repository/pull/17810

**Pull request merged**
