### PR TITLE
Add script for benchmarking

### PR DESCRIPTION
**Pull request by gaborigloi**
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
Example output:
```
~/s/nbd (benchmark|…) $ make benchmark
jbuilder build @install --dev
./benchmark.sh
+ dd if=/dev/zero of=/tmp/test bs=1M count=100
100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.0726483 s, 1.4 GB/s
+ SERVER_PROCESS=9966
+ echo 9966
9966
+ trap stop_server EXIT
+ sudo modprobe nbd
+ _build/default/cli/main.exe serve --no-tls /tmp/test
+ sudo nbd-client -N test localhost /dev/nbd0
Negotiation: main.exe: Server.connect: Starting fixed-newstyle negotiation
..main.exe: Server.serve: Serving new client, read_only = false
size = 100MB
bs=1024, sz=104857600 bytes
+ trap stop_client EXIT
+ sudo hdparm -t /dev/nbd0

/dev/nbd0:
 Timing buffered disk reads: 100 MB in  0.10 seconds = 957.84 MB/sec
+ sudo hdparm -t /dev/nbd0

/dev/nbd0:
 Timing buffered disk reads: 100 MB in  0.10 seconds = 1025.76 MB/sec
+ sudo hdparm -t /dev/nbd0

/dev/nbd0:
 Timing buffered disk reads: 100 MB in  0.08 seconds = 1201.45 MB/sec
+ sudo hdparm -t /dev/nbd0

/dev/nbd0:
 Timing buffered disk reads: 100 MB in  0.09 seconds = 1171.28 MB/sec
+ sudo hdparm -t /dev/nbd0

/dev/nbd0:
 Timing buffered disk reads: 100 MB in  0.09 seconds = 1088.84 MB/sec
+ stop_client
+ sudo nbd-client -d /dev/nbd0
disconnect, sock, done
main.exe: Server.serve: Received NBD_CMD_DISC, disconnecting
+ stop_server
++ jobs -p
+ kill 9966
~/s/nbd (benchmark|…) $ 
```

**Comment by gaborigloi** [comment]
Thanks for mentioning that, I ran it and it took quite long - maybe it's still good to have this faster benchmark with hdparm, but I guess I could mention this in a comment.

**Comment by edwintorok** [comment]
We could also probably reuse some of the existing benchmarks in xenrt/rage.

**Comment by lindig** [comment]
Any reason not to merge this? It does no harm and can be improved independently.

**Pull request merged**
