### PR TITLE
[WIP] Enable Travis but don't upload documentation

### PR DESCRIPTION
**Pull request by gaborigloi**
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
Is there is ticket for this? If not, could you motivate the two changes?

* Why do we need the new Opam constraint
* The `travis.yml` change looks fine but why are we no longer uploading documentation?

**Comment by gaborigloi** [comment]
@lindig sorry for leaving this here, it is still WIP - it did not build with the original OPAM constraints, so I need to adjust them.
The documentation is already uploaded from the `master` branch for the newest version, so we should not overwrite it from this branch.

**Comment by mseri** [comment]
It should work with the upstream opamfile with 2.1.3. Doesn't it?

**Comment by gaborigloi** [comment]
Oh I see, we should use the `opam` file from `xs-opam` that actually works, and add `xs-opam` as the remote, just like we did for the Travis config of the other repos.

**Comment by gaborigloi** [comment]
For some reason we got a cyclic dependency:
∗  js_of_ocaml.2.8.3 -> ∗  logs.0.6.2 -> ∗  bos.0.1.4 -> ∗  base64.2.1.2 -> ∗  js_of_ocaml.2.8.3

**Comment by gaborigloi** [comment]
Closing, I'll reopen this once I get it to work, sorry for the spam.

**Comment by gaborigloi** [comment]
Seems to be the same circular dependency as here: https://github.com/ocaml/opam-repository/issues/8048

**Comment by gaborigloi** [comment]
Opened another PR, which doesn't have the cyclic dependency issue: https://github.com/xapi-project/nbd/pull/57

**Pull request closed without merging**
