### PR TITLE
connect does not return a result anymore

### PR DESCRIPTION
**Pull request by hannesm**
in preparation of the MirageOS3 release.

no need to merge until the release, though

### CODE REVIEW

**Comment by hannesm** [comment]
same as in https://github.com/mirage/ocaml-qcow/pull/27 I've no idea what the code does. tests run fine (but there are only few tests).  see https://lists.xenproject.org/archives/html/mirageos-devel/2016-09/msg00050.html for the motivation of the change (which landed in mirage master (unreleased) recently https://github.com/mirage/mirage/pull/602)

**Comment by jonludlam** [comment]
Thanks @hannesm. If I merge this as-is, it'll bring in your opam remote, and I don't think we really want that. It's probably better to remove that commit and wait until the releases of the dependent packages have happened, then retry travis for our green tick?

**Comment by hannesm** [comment]
I force-pushed to use the "official" mirage-dev opam remote ;)
Yes, it might be sensible to wait till Mirage3 appears (I expect there will be more API changes).

**Comment by jonludlam** [comment]
OK thanks, I'll leave this here until the release.

**Comment by avsm** [comment]
could this be merged with latest nbd release? It also fixes a 4.03 Result build failure

**Comment by hannesm** [comment]
@avsm I just rebased this on top of master

**Comment by djs55** [comment]
I've included this and more Mirage OS 3 changes in #34

**Comment by hannesm** [comment]
thx @djs55, closing this PR in favor of #34 which is more complete

**Pull request closed without merging**
