### PR TITLE
CP-22035: lib support for TLS channels

### PR DESCRIPTION
**Pull request by thomassa**
Laying the groundwork for adding support for the TLS-related parts
of the NBD protocol: that future work will use the TLS channels.

### CODE REVIEW

**Comment by jonludlam** [comment]
I'm not quite sure I understand how the new types and functions are intended to be used. I think an example would be helpful (and would tease out if there are any issues with the current set of functions/types).

For example, to turn a connection into a TLS one right now involves creating a new channel type, which implies the loop that responds to the incoming stream must return a new channel - is this the intended use?

**Comment by djs55** [comment]
I think `ssl` and `lwt_ssl` are Unix-specific libraries which won't work in Mirage :( Is it possible to keep things abstract in the core `nbd` library and only bring in Unix in`nbd.lwt`? Currently the core library is Mirage friendly, and only the `nbd.lwt` package links against `lwt.unix` and `io-page.unix`.

**Comment by jonludlam** [comment]
Good point.

**Comment by thomassa** [comment]
Do address @djs55's comment I've moved that Unix-specific implementation code from the Channel module (nbd library) to the Nbd_lwt_unix module (nbd-lwt library).
But making the corresponding changes in the _oasis file, I find it doesn't build without leaving "ssl" in the BuildDepends section of the nbd library. I've not worked out why yet.

**Comment by thomassa** [comment]
There are still some other changes I should make here before we merge though.
Feel free to close the pull-request for the time being.

**Comment by lindig** [comment]
As @thomassa said, this is not ready to be merged - closing it for now.

**Pull request closed without merging**
