### PR TITLE
Server: Add support for read-only exports and don't terminate connection in case of write errors

### PR DESCRIPTION
**Pull request by gaborigloi**

### CODE REVIEW

**Comment by gaborigloi** [comment]
This fixes https://github.com/xapi-project/nbd/issues/105 - however, since I'm not sure I interpreted the protocol correctly, I'm happy to just add read-only support but not change the server's behaviour for NBD_CMD_WRITE to continue in case of write errors - after all, who knows whether the client will still try to send the data it wants to write, when it receives EPERM from the server after sending the header for NBD_CMD_WRITE. So maybe I shouldn't change the exiting behaiour. I already have a branch fix only adds read-write support, but does not change this behaviour, so I'm happy to submit that instead.

**Comment by gaborigloi** [comment]
I think it should be fine to merge this one, instead of #107, because I added the continuation of the `loop` to the write handler anyway, to fix #43 , and there is no special reason I only continued the loop in case everything is OK, I just followed the pattern of the NBD_CMD_READ handler.

**Comment by gaborigloi** [comment]
As I said in https://github.com/xapi-project/nbd/pull/107 , now I actually think we should merge that one instead of this PR.

**Comment by mseri** [comment]
I don't have a good feeling about continuing the loop in case of errors, especially if we are not able to guarantee a sane behaviour of successive write attempts. I'd rather close this and merge #107

**Comment by gaborigloi** [comment]
Sounds good, closing.

**Pull request closed without merging**
