### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by gaborigloi**

### CODE REVIEW

**Comment by gaborigloi** [comment]
Hmm, got an error that I still need to fix:
```
# ocamlfind: Package `ppx_cstruct' not found - required by `cstruct.ppx'
```

**Comment by gaborigloi** [comment]
I think it works fine now. The error happens because for some reason `uri` is downgraded to an old version, and this cause one of the tests of `mirage-block-unix` to fail.

**Comment by mseri** [comment]
Weird

**Comment by gaborigloi** [comment]
Raised https://github.com/mirage/mirage-block-unix/issues/79 about the test failure of `mirage-block-unix`.

**Pull request merged**
